title: Binary equilibrium
description: Illustrative examples of a multi-objective program subject to a binary quasi-equilibrium
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
