* -----------------------------------------------------
* XLS2GMS 2.8      24.4.6 r52609 Released Jun 26, 2015 VS8 x86 32bit/MS Windows 
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Users\huppmann\Documents\GAMSMOPBQE_numerical\input_data\input_UC_dh.xlsx
* Sheet:       wind_test(Sheet5)
* Range:       $AA$4:$AB$23
* -----------------------------------------------------
     column1
w1   300    
w2   300    
w3   600    
w4   600    
w5   300    
w6   600    
w7   600    
w8   300    
w9   300    
w10  150    
w11  300    
w12  300    
w13  300    
w14  150    
w15  600    
w16  600    
w17  150    
w18  300    
w19  150    
* -----------------------------------------------------
